
services:
  db:
    image: mariadb
    volumes:
      # Use bind mount for now, so I can manually modify the content
      - ./maria_db:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wp_vietrc
      MYSQL_USER: vietrc
      MYSQL_PASSWORD: test1234
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_USER: vietrc
      MYSQL_PASSWORD: test1234
      MYSQL_ROOT_PASSWORD: somewordpress
    ports:
      - 40001:80
  wordpress:
    depends_on:
      - db
    image: wordpress
    volumes:
      - ./wp_data:/var/www/html
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: wp_vietrc
      WORDPRESS_DB_USER: vietrc
      WORDPRESS_DB_PASSWORD: test1234
    ports:
      - 40002:80


